## usethis namespace: start
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_ribbon
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 scale_x_date
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom grDevices gray
#' @importFrom numDeriv jacobian
#' @importFrom Rcpp sourceCpp
#' @importFrom robustbase glmrob
#' @importFrom stats acf
#' @importFrom stats coef
#' @importFrom stats delete.response
#' @importFrom stats fitted
#' @importFrom stats glm.fit
#' @importFrom stats is.empty.model
#' @importFrom stats model.frame
#' @importFrom stats model.matrix
#' @importFrom stats model.offset
#' @importFrom stats model.response
#' @importFrom stats optim
#' @importFrom stats pnorm
#' @importFrom stats poisson
#' @importFrom stats printCoefmat
#' @importFrom stats qpois
#' @importFrom stats terms
#' @useDynLib odes, .registration = TRUE
## usethis namespace: end
NULL
