# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_loglik <- function(eta, y, alpha) {
    .Call(`_odes_compute_loglik`, eta, y, alpha)
}

compute_scores <- function(eta, x, y, alpha) {
    .Call(`_odes_compute_scores`, eta, x, y, alpha)
}

simulate_odes <- function(eta, alpha) {
    .Call(`_odes_simulate_odes`, eta, alpha)
}

